name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PATH: ${{ github.env.PATH }}:/usr/bin  # 全局 PATH 设置
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Install xargs
        run: sudo apt-get install -y findutils
      - name: Verify xargs
        run: |
          which xargs
          xargs --version
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build -Dorg.gradle.processes.xargs.path=/usr/bin/xargs
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/